//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTier.LoaiSanPham_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoaiSanPham", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class LoaiSanPham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoTaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((this.MaLoaiField.Equals(value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoTaLoai {
            get {
                return this.MoTaLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.MoTaLoaiField, value) != true)) {
                    this.MoTaLoaiField = value;
                    this.RaisePropertyChanged("MoTaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLoai {
            get {
                return this.TenLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiField, value) != true)) {
                    this.TenLoaiField = value;
                    this.RaisePropertyChanged("TenLoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoaiSanPham_ServiceReference.ILoaiSanPhamService")]
    public interface ILoaiSanPhamService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiSanPhamService/GetLoaiSanPhamById", ReplyAction="http://tempuri.org/ILoaiSanPhamService/GetLoaiSanPhamByIdResponse")]
        WinTier.LoaiSanPham_ServiceReference.LoaiSanPham GetLoaiSanPhamById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiSanPhamService/GetLoaiSanPhamById", ReplyAction="http://tempuri.org/ILoaiSanPhamService/GetLoaiSanPhamByIdResponse")]
        System.Threading.Tasks.Task<WinTier.LoaiSanPham_ServiceReference.LoaiSanPham> GetLoaiSanPhamByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiSanPhamService/GetAllLoaiSanPham", ReplyAction="http://tempuri.org/ILoaiSanPhamService/GetAllLoaiSanPhamResponse")]
        WinTier.LoaiSanPham_ServiceReference.LoaiSanPham[] GetAllLoaiSanPham();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiSanPhamService/GetAllLoaiSanPham", ReplyAction="http://tempuri.org/ILoaiSanPhamService/GetAllLoaiSanPhamResponse")]
        System.Threading.Tasks.Task<WinTier.LoaiSanPham_ServiceReference.LoaiSanPham[]> GetAllLoaiSanPhamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiSanPhamService/InsertLoaiSanPham", ReplyAction="http://tempuri.org/ILoaiSanPhamService/InsertLoaiSanPhamResponse")]
        void InsertLoaiSanPham(WinTier.LoaiSanPham_ServiceReference.LoaiSanPham obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiSanPhamService/InsertLoaiSanPham", ReplyAction="http://tempuri.org/ILoaiSanPhamService/InsertLoaiSanPhamResponse")]
        System.Threading.Tasks.Task InsertLoaiSanPhamAsync(WinTier.LoaiSanPham_ServiceReference.LoaiSanPham obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiSanPhamService/UpdateLoaiSanPham", ReplyAction="http://tempuri.org/ILoaiSanPhamService/UpdateLoaiSanPhamResponse")]
        void UpdateLoaiSanPham(WinTier.LoaiSanPham_ServiceReference.LoaiSanPham obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiSanPhamService/UpdateLoaiSanPham", ReplyAction="http://tempuri.org/ILoaiSanPhamService/UpdateLoaiSanPhamResponse")]
        System.Threading.Tasks.Task UpdateLoaiSanPhamAsync(WinTier.LoaiSanPham_ServiceReference.LoaiSanPham obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiSanPhamService/DeleteLoaiSanPham", ReplyAction="http://tempuri.org/ILoaiSanPhamService/DeleteLoaiSanPhamResponse")]
        void DeleteLoaiSanPham(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiSanPhamService/DeleteLoaiSanPham", ReplyAction="http://tempuri.org/ILoaiSanPhamService/DeleteLoaiSanPhamResponse")]
        System.Threading.Tasks.Task DeleteLoaiSanPhamAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoaiSanPhamServiceChannel : WinTier.LoaiSanPham_ServiceReference.ILoaiSanPhamService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoaiSanPhamServiceClient : System.ServiceModel.ClientBase<WinTier.LoaiSanPham_ServiceReference.ILoaiSanPhamService>, WinTier.LoaiSanPham_ServiceReference.ILoaiSanPhamService {
        
        public LoaiSanPhamServiceClient() {
        }
        
        public LoaiSanPhamServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoaiSanPhamServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoaiSanPhamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoaiSanPhamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinTier.LoaiSanPham_ServiceReference.LoaiSanPham GetLoaiSanPhamById(int id) {
            return base.Channel.GetLoaiSanPhamById(id);
        }
        
        public System.Threading.Tasks.Task<WinTier.LoaiSanPham_ServiceReference.LoaiSanPham> GetLoaiSanPhamByIdAsync(int id) {
            return base.Channel.GetLoaiSanPhamByIdAsync(id);
        }
        
        public WinTier.LoaiSanPham_ServiceReference.LoaiSanPham[] GetAllLoaiSanPham() {
            return base.Channel.GetAllLoaiSanPham();
        }
        
        public System.Threading.Tasks.Task<WinTier.LoaiSanPham_ServiceReference.LoaiSanPham[]> GetAllLoaiSanPhamAsync() {
            return base.Channel.GetAllLoaiSanPhamAsync();
        }
        
        public void InsertLoaiSanPham(WinTier.LoaiSanPham_ServiceReference.LoaiSanPham obj) {
            base.Channel.InsertLoaiSanPham(obj);
        }
        
        public System.Threading.Tasks.Task InsertLoaiSanPhamAsync(WinTier.LoaiSanPham_ServiceReference.LoaiSanPham obj) {
            return base.Channel.InsertLoaiSanPhamAsync(obj);
        }
        
        public void UpdateLoaiSanPham(WinTier.LoaiSanPham_ServiceReference.LoaiSanPham obj) {
            base.Channel.UpdateLoaiSanPham(obj);
        }
        
        public System.Threading.Tasks.Task UpdateLoaiSanPhamAsync(WinTier.LoaiSanPham_ServiceReference.LoaiSanPham obj) {
            return base.Channel.UpdateLoaiSanPhamAsync(obj);
        }
        
        public void DeleteLoaiSanPham(int id) {
            base.Channel.DeleteLoaiSanPham(id);
        }
        
        public System.Threading.Tasks.Task DeleteLoaiSanPhamAsync(int id) {
            return base.Channel.DeleteLoaiSanPhamAsync(id);
        }
    }
}
