//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTier.NhaSanXuat_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhaSanXuat", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class NhaSanXuat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiThieuNSXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNSXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNSXField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GioiThieuNSX {
            get {
                return this.GioiThieuNSXField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiThieuNSXField, value) != true)) {
                    this.GioiThieuNSXField = value;
                    this.RaisePropertyChanged("GioiThieuNSX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNSX {
            get {
                return this.MaNSXField;
            }
            set {
                if ((this.MaNSXField.Equals(value) != true)) {
                    this.MaNSXField = value;
                    this.RaisePropertyChanged("MaNSX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNSX {
            get {
                return this.TenNSXField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNSXField, value) != true)) {
                    this.TenNSXField = value;
                    this.RaisePropertyChanged("TenNSX");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NhaSanXuat_ServiceReference.INhaSanXuatService")]
    public interface INhaSanXuatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSanXuatService/GetNhaSanXuatById", ReplyAction="http://tempuri.org/INhaSanXuatService/GetNhaSanXuatByIdResponse")]
        WinTier.NhaSanXuat_ServiceReference.NhaSanXuat GetNhaSanXuatById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSanXuatService/GetNhaSanXuatById", ReplyAction="http://tempuri.org/INhaSanXuatService/GetNhaSanXuatByIdResponse")]
        System.Threading.Tasks.Task<WinTier.NhaSanXuat_ServiceReference.NhaSanXuat> GetNhaSanXuatByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSanXuatService/GetAllNhaSanXuat", ReplyAction="http://tempuri.org/INhaSanXuatService/GetAllNhaSanXuatResponse")]
        WinTier.NhaSanXuat_ServiceReference.NhaSanXuat[] GetAllNhaSanXuat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSanXuatService/GetAllNhaSanXuat", ReplyAction="http://tempuri.org/INhaSanXuatService/GetAllNhaSanXuatResponse")]
        System.Threading.Tasks.Task<WinTier.NhaSanXuat_ServiceReference.NhaSanXuat[]> GetAllNhaSanXuatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSanXuatService/InsertNhaSanXuat", ReplyAction="http://tempuri.org/INhaSanXuatService/InsertNhaSanXuatResponse")]
        void InsertNhaSanXuat(WinTier.NhaSanXuat_ServiceReference.NhaSanXuat obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSanXuatService/InsertNhaSanXuat", ReplyAction="http://tempuri.org/INhaSanXuatService/InsertNhaSanXuatResponse")]
        System.Threading.Tasks.Task InsertNhaSanXuatAsync(WinTier.NhaSanXuat_ServiceReference.NhaSanXuat obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSanXuatService/UpdateNhaSanXuat", ReplyAction="http://tempuri.org/INhaSanXuatService/UpdateNhaSanXuatResponse")]
        void UpdateNhaSanXuat(WinTier.NhaSanXuat_ServiceReference.NhaSanXuat obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSanXuatService/UpdateNhaSanXuat", ReplyAction="http://tempuri.org/INhaSanXuatService/UpdateNhaSanXuatResponse")]
        System.Threading.Tasks.Task UpdateNhaSanXuatAsync(WinTier.NhaSanXuat_ServiceReference.NhaSanXuat obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSanXuatService/DeleteNhaSanXuat", ReplyAction="http://tempuri.org/INhaSanXuatService/DeleteNhaSanXuatResponse")]
        void DeleteNhaSanXuat(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhaSanXuatService/DeleteNhaSanXuat", ReplyAction="http://tempuri.org/INhaSanXuatService/DeleteNhaSanXuatResponse")]
        System.Threading.Tasks.Task DeleteNhaSanXuatAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INhaSanXuatServiceChannel : WinTier.NhaSanXuat_ServiceReference.INhaSanXuatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NhaSanXuatServiceClient : System.ServiceModel.ClientBase<WinTier.NhaSanXuat_ServiceReference.INhaSanXuatService>, WinTier.NhaSanXuat_ServiceReference.INhaSanXuatService {
        
        public NhaSanXuatServiceClient() {
        }
        
        public NhaSanXuatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NhaSanXuatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NhaSanXuatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NhaSanXuatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinTier.NhaSanXuat_ServiceReference.NhaSanXuat GetNhaSanXuatById(int id) {
            return base.Channel.GetNhaSanXuatById(id);
        }
        
        public System.Threading.Tasks.Task<WinTier.NhaSanXuat_ServiceReference.NhaSanXuat> GetNhaSanXuatByIdAsync(int id) {
            return base.Channel.GetNhaSanXuatByIdAsync(id);
        }
        
        public WinTier.NhaSanXuat_ServiceReference.NhaSanXuat[] GetAllNhaSanXuat() {
            return base.Channel.GetAllNhaSanXuat();
        }
        
        public System.Threading.Tasks.Task<WinTier.NhaSanXuat_ServiceReference.NhaSanXuat[]> GetAllNhaSanXuatAsync() {
            return base.Channel.GetAllNhaSanXuatAsync();
        }
        
        public void InsertNhaSanXuat(WinTier.NhaSanXuat_ServiceReference.NhaSanXuat obj) {
            base.Channel.InsertNhaSanXuat(obj);
        }
        
        public System.Threading.Tasks.Task InsertNhaSanXuatAsync(WinTier.NhaSanXuat_ServiceReference.NhaSanXuat obj) {
            return base.Channel.InsertNhaSanXuatAsync(obj);
        }
        
        public void UpdateNhaSanXuat(WinTier.NhaSanXuat_ServiceReference.NhaSanXuat obj) {
            base.Channel.UpdateNhaSanXuat(obj);
        }
        
        public System.Threading.Tasks.Task UpdateNhaSanXuatAsync(WinTier.NhaSanXuat_ServiceReference.NhaSanXuat obj) {
            return base.Channel.UpdateNhaSanXuatAsync(obj);
        }
        
        public void DeleteNhaSanXuat(int id) {
            base.Channel.DeleteNhaSanXuat(id);
        }
        
        public System.Threading.Tasks.Task DeleteNhaSanXuatAsync(int id) {
            return base.Channel.DeleteNhaSanXuatAsync(id);
        }
    }
}
