//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTier.DonDatHang_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonDatHang", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class DonDatHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiNhanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiNhanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailKhachHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GhiChuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDonDatHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaKhachHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaNhanVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayGiaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayTaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhachHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNguoiNhanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNguoiTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TongTienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TrangThaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> XuatKhoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChiNhan {
            get {
                return this.DiaChiNhanField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiNhanField, value) != true)) {
                    this.DiaChiNhanField = value;
                    this.RaisePropertyChanged("DiaChiNhan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChiTT {
            get {
                return this.DiaChiTTField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiTTField, value) != true)) {
                    this.DiaChiTTField = value;
                    this.RaisePropertyChanged("DiaChiTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DienThoaiNhan {
            get {
                return this.DienThoaiNhanField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiNhanField, value) != true)) {
                    this.DienThoaiNhanField = value;
                    this.RaisePropertyChanged("DienThoaiNhan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DienThoaiTT {
            get {
                return this.DienThoaiTTField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiTTField, value) != true)) {
                    this.DienThoaiTTField = value;
                    this.RaisePropertyChanged("DienThoaiTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailKhachHang {
            get {
                return this.EmailKhachHangField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailKhachHangField, value) != true)) {
                    this.EmailKhachHangField = value;
                    this.RaisePropertyChanged("EmailKhachHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GhiChu {
            get {
                return this.GhiChuField;
            }
            set {
                if ((object.ReferenceEquals(this.GhiChuField, value) != true)) {
                    this.GhiChuField = value;
                    this.RaisePropertyChanged("GhiChu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDonDatHang {
            get {
                return this.MaDonDatHangField;
            }
            set {
                if ((this.MaDonDatHangField.Equals(value) != true)) {
                    this.MaDonDatHangField = value;
                    this.RaisePropertyChanged("MaDonDatHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaKhachHang {
            get {
                return this.MaKhachHangField;
            }
            set {
                if ((this.MaKhachHangField.Equals(value) != true)) {
                    this.MaKhachHangField = value;
                    this.RaisePropertyChanged("MaKhachHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaNhanVien {
            get {
                return this.MaNhanVienField;
            }
            set {
                if ((this.MaNhanVienField.Equals(value) != true)) {
                    this.MaNhanVienField = value;
                    this.RaisePropertyChanged("MaNhanVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayGiao {
            get {
                return this.NgayGiaoField;
            }
            set {
                if ((this.NgayGiaoField.Equals(value) != true)) {
                    this.NgayGiaoField = value;
                    this.RaisePropertyChanged("NgayGiao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayTao {
            get {
                return this.NgayTaoField;
            }
            set {
                if ((this.NgayTaoField.Equals(value) != true)) {
                    this.NgayTaoField = value;
                    this.RaisePropertyChanged("NgayTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenKhachHang {
            get {
                return this.TenKhachHangField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhachHangField, value) != true)) {
                    this.TenKhachHangField = value;
                    this.RaisePropertyChanged("TenKhachHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNguoiNhan {
            get {
                return this.TenNguoiNhanField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNguoiNhanField, value) != true)) {
                    this.TenNguoiNhanField = value;
                    this.RaisePropertyChanged("TenNguoiNhan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNguoiTT {
            get {
                return this.TenNguoiTTField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNguoiTTField, value) != true)) {
                    this.TenNguoiTTField = value;
                    this.RaisePropertyChanged("TenNguoiTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((this.TrangThaiField.Equals(value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> XuatKho {
            get {
                return this.XuatKhoField;
            }
            set {
                if ((this.XuatKhoField.Equals(value) != true)) {
                    this.XuatKhoField = value;
                    this.RaisePropertyChanged("XuatKho");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DonDatHang_ServiceReference.IDonDatHangService")]
    public interface IDonDatHangService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonDatHangService/GetDonDatHangById", ReplyAction="http://tempuri.org/IDonDatHangService/GetDonDatHangByIdResponse")]
        WinTier.DonDatHang_ServiceReference.DonDatHang GetDonDatHangById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonDatHangService/GetDonDatHangById", ReplyAction="http://tempuri.org/IDonDatHangService/GetDonDatHangByIdResponse")]
        System.Threading.Tasks.Task<WinTier.DonDatHang_ServiceReference.DonDatHang> GetDonDatHangByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonDatHangService/GetAllDonDatHang", ReplyAction="http://tempuri.org/IDonDatHangService/GetAllDonDatHangResponse")]
        WinTier.DonDatHang_ServiceReference.DonDatHang[] GetAllDonDatHang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonDatHangService/GetAllDonDatHang", ReplyAction="http://tempuri.org/IDonDatHangService/GetAllDonDatHangResponse")]
        System.Threading.Tasks.Task<WinTier.DonDatHang_ServiceReference.DonDatHang[]> GetAllDonDatHangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonDatHangService/InsertDonDatHang", ReplyAction="http://tempuri.org/IDonDatHangService/InsertDonDatHangResponse")]
        void InsertDonDatHang(WinTier.DonDatHang_ServiceReference.DonDatHang obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonDatHangService/InsertDonDatHang", ReplyAction="http://tempuri.org/IDonDatHangService/InsertDonDatHangResponse")]
        System.Threading.Tasks.Task InsertDonDatHangAsync(WinTier.DonDatHang_ServiceReference.DonDatHang obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonDatHangService/UpdateDonDatHang", ReplyAction="http://tempuri.org/IDonDatHangService/UpdateDonDatHangResponse")]
        void UpdateDonDatHang(WinTier.DonDatHang_ServiceReference.DonDatHang obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonDatHangService/UpdateDonDatHang", ReplyAction="http://tempuri.org/IDonDatHangService/UpdateDonDatHangResponse")]
        System.Threading.Tasks.Task UpdateDonDatHangAsync(WinTier.DonDatHang_ServiceReference.DonDatHang obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonDatHangService/DeleteDonDatHang", ReplyAction="http://tempuri.org/IDonDatHangService/DeleteDonDatHangResponse")]
        void DeleteDonDatHang(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonDatHangService/DeleteDonDatHang", ReplyAction="http://tempuri.org/IDonDatHangService/DeleteDonDatHangResponse")]
        System.Threading.Tasks.Task DeleteDonDatHangAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonDatHangService/GetMaxDonHangId", ReplyAction="http://tempuri.org/IDonDatHangService/GetMaxDonHangIdResponse")]
        int GetMaxDonHangId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonDatHangService/GetMaxDonHangId", ReplyAction="http://tempuri.org/IDonDatHangService/GetMaxDonHangIdResponse")]
        System.Threading.Tasks.Task<int> GetMaxDonHangIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonDatHangService/ThongKeDoanhThu", ReplyAction="http://tempuri.org/IDonDatHangService/ThongKeDoanhThuResponse")]
        WinTier.DonDatHang_ServiceReference.DonDatHang[] ThongKeDoanhThu(System.DateTime ngaytu, System.DateTime ngayden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDonDatHangService/ThongKeDoanhThu", ReplyAction="http://tempuri.org/IDonDatHangService/ThongKeDoanhThuResponse")]
        System.Threading.Tasks.Task<WinTier.DonDatHang_ServiceReference.DonDatHang[]> ThongKeDoanhThuAsync(System.DateTime ngaytu, System.DateTime ngayden);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDonDatHangServiceChannel : WinTier.DonDatHang_ServiceReference.IDonDatHangService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DonDatHangServiceClient : System.ServiceModel.ClientBase<WinTier.DonDatHang_ServiceReference.IDonDatHangService>, WinTier.DonDatHang_ServiceReference.IDonDatHangService {
        
        public DonDatHangServiceClient() {
        }
        
        public DonDatHangServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DonDatHangServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DonDatHangServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DonDatHangServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinTier.DonDatHang_ServiceReference.DonDatHang GetDonDatHangById(int id) {
            return base.Channel.GetDonDatHangById(id);
        }
        
        public System.Threading.Tasks.Task<WinTier.DonDatHang_ServiceReference.DonDatHang> GetDonDatHangByIdAsync(int id) {
            return base.Channel.GetDonDatHangByIdAsync(id);
        }
        
        public WinTier.DonDatHang_ServiceReference.DonDatHang[] GetAllDonDatHang() {
            return base.Channel.GetAllDonDatHang();
        }
        
        public System.Threading.Tasks.Task<WinTier.DonDatHang_ServiceReference.DonDatHang[]> GetAllDonDatHangAsync() {
            return base.Channel.GetAllDonDatHangAsync();
        }
        
        public void InsertDonDatHang(WinTier.DonDatHang_ServiceReference.DonDatHang obj) {
            base.Channel.InsertDonDatHang(obj);
        }
        
        public System.Threading.Tasks.Task InsertDonDatHangAsync(WinTier.DonDatHang_ServiceReference.DonDatHang obj) {
            return base.Channel.InsertDonDatHangAsync(obj);
        }
        
        public void UpdateDonDatHang(WinTier.DonDatHang_ServiceReference.DonDatHang obj) {
            base.Channel.UpdateDonDatHang(obj);
        }
        
        public System.Threading.Tasks.Task UpdateDonDatHangAsync(WinTier.DonDatHang_ServiceReference.DonDatHang obj) {
            return base.Channel.UpdateDonDatHangAsync(obj);
        }
        
        public void DeleteDonDatHang(int id) {
            base.Channel.DeleteDonDatHang(id);
        }
        
        public System.Threading.Tasks.Task DeleteDonDatHangAsync(int id) {
            return base.Channel.DeleteDonDatHangAsync(id);
        }
        
        public int GetMaxDonHangId() {
            return base.Channel.GetMaxDonHangId();
        }
        
        public System.Threading.Tasks.Task<int> GetMaxDonHangIdAsync() {
            return base.Channel.GetMaxDonHangIdAsync();
        }
        
        public WinTier.DonDatHang_ServiceReference.DonDatHang[] ThongKeDoanhThu(System.DateTime ngaytu, System.DateTime ngayden) {
            return base.Channel.ThongKeDoanhThu(ngaytu, ngayden);
        }
        
        public System.Threading.Tasks.Task<WinTier.DonDatHang_ServiceReference.DonDatHang[]> ThongKeDoanhThuAsync(System.DateTime ngaytu, System.DateTime ngayden) {
            return base.Channel.ThongKeDoanhThuAsync(ngaytu, ngayden);
        }
    }
}
