//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTier.NhanVien_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhanVien", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class NhanVien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChucVuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNhanVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChucVu {
            get {
                return this.ChucVuField;
            }
            set {
                if ((this.ChucVuField.Equals(value) != true)) {
                    this.ChucVuField = value;
                    this.RaisePropertyChanged("ChucVu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNhanVien {
            get {
                return this.MaNhanVienField;
            }
            set {
                if ((this.MaNhanVienField.Equals(value) != true)) {
                    this.MaNhanVienField = value;
                    this.RaisePropertyChanged("MaNhanVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoDT {
            get {
                return this.SoDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SoDTField, value) != true)) {
                    this.SoDTField = value;
                    this.RaisePropertyChanged("SoDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NhanVien_ServiceReference.INhanVienService")]
    public interface INhanVienService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/GetNhanVienById", ReplyAction="http://tempuri.org/INhanVienService/GetNhanVienByIdResponse")]
        WinTier.NhanVien_ServiceReference.NhanVien GetNhanVienById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/GetNhanVienById", ReplyAction="http://tempuri.org/INhanVienService/GetNhanVienByIdResponse")]
        System.Threading.Tasks.Task<WinTier.NhanVien_ServiceReference.NhanVien> GetNhanVienByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/GetAllNhanVien", ReplyAction="http://tempuri.org/INhanVienService/GetAllNhanVienResponse")]
        WinTier.NhanVien_ServiceReference.NhanVien[] GetAllNhanVien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/GetAllNhanVien", ReplyAction="http://tempuri.org/INhanVienService/GetAllNhanVienResponse")]
        System.Threading.Tasks.Task<WinTier.NhanVien_ServiceReference.NhanVien[]> GetAllNhanVienAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/InsertNhanVien", ReplyAction="http://tempuri.org/INhanVienService/InsertNhanVienResponse")]
        void InsertNhanVien(WinTier.NhanVien_ServiceReference.NhanVien obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/InsertNhanVien", ReplyAction="http://tempuri.org/INhanVienService/InsertNhanVienResponse")]
        System.Threading.Tasks.Task InsertNhanVienAsync(WinTier.NhanVien_ServiceReference.NhanVien obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/UpdateNhanVien", ReplyAction="http://tempuri.org/INhanVienService/UpdateNhanVienResponse")]
        void UpdateNhanVien(WinTier.NhanVien_ServiceReference.NhanVien obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/UpdateNhanVien", ReplyAction="http://tempuri.org/INhanVienService/UpdateNhanVienResponse")]
        System.Threading.Tasks.Task UpdateNhanVienAsync(WinTier.NhanVien_ServiceReference.NhanVien obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/DeleteNhanVien", ReplyAction="http://tempuri.org/INhanVienService/DeleteNhanVienResponse")]
        void DeleteNhanVien(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/DeleteNhanVien", ReplyAction="http://tempuri.org/INhanVienService/DeleteNhanVienResponse")]
        System.Threading.Tasks.Task DeleteNhanVienAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INhanVienServiceChannel : WinTier.NhanVien_ServiceReference.INhanVienService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NhanVienServiceClient : System.ServiceModel.ClientBase<WinTier.NhanVien_ServiceReference.INhanVienService>, WinTier.NhanVien_ServiceReference.INhanVienService {
        
        public NhanVienServiceClient() {
        }
        
        public NhanVienServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NhanVienServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NhanVienServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NhanVienServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinTier.NhanVien_ServiceReference.NhanVien GetNhanVienById(int id) {
            return base.Channel.GetNhanVienById(id);
        }
        
        public System.Threading.Tasks.Task<WinTier.NhanVien_ServiceReference.NhanVien> GetNhanVienByIdAsync(int id) {
            return base.Channel.GetNhanVienByIdAsync(id);
        }
        
        public WinTier.NhanVien_ServiceReference.NhanVien[] GetAllNhanVien() {
            return base.Channel.GetAllNhanVien();
        }
        
        public System.Threading.Tasks.Task<WinTier.NhanVien_ServiceReference.NhanVien[]> GetAllNhanVienAsync() {
            return base.Channel.GetAllNhanVienAsync();
        }
        
        public void InsertNhanVien(WinTier.NhanVien_ServiceReference.NhanVien obj) {
            base.Channel.InsertNhanVien(obj);
        }
        
        public System.Threading.Tasks.Task InsertNhanVienAsync(WinTier.NhanVien_ServiceReference.NhanVien obj) {
            return base.Channel.InsertNhanVienAsync(obj);
        }
        
        public void UpdateNhanVien(WinTier.NhanVien_ServiceReference.NhanVien obj) {
            base.Channel.UpdateNhanVien(obj);
        }
        
        public System.Threading.Tasks.Task UpdateNhanVienAsync(WinTier.NhanVien_ServiceReference.NhanVien obj) {
            return base.Channel.UpdateNhanVienAsync(obj);
        }
        
        public void DeleteNhanVien(int id) {
            base.Channel.DeleteNhanVien(id);
        }
        
        public System.Threading.Tasks.Task DeleteNhanVienAsync(int id) {
            return base.Channel.DeleteNhanVienAsync(id);
        }
    }
}
