//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTier.ChiTietPhieuNhap_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChiTietPhieuNhap", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class ChiTietPhieuNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DonGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaPhieuNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TongCongNhapField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaPhieuNhap {
            get {
                return this.MaPhieuNhapField;
            }
            set {
                if ((this.MaPhieuNhapField.Equals(value) != true)) {
                    this.MaPhieuNhapField = value;
                    this.RaisePropertyChanged("MaPhieuNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSanPham {
            get {
                return this.MaSanPhamField;
            }
            set {
                if ((this.MaSanPhamField.Equals(value) != true)) {
                    this.MaSanPhamField = value;
                    this.RaisePropertyChanged("MaSanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuongNhap {
            get {
                return this.SoLuongNhapField;
            }
            set {
                if ((this.SoLuongNhapField.Equals(value) != true)) {
                    this.SoLuongNhapField = value;
                    this.RaisePropertyChanged("SoLuongNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TongCongNhap {
            get {
                return this.TongCongNhapField;
            }
            set {
                if ((this.TongCongNhapField.Equals(value) != true)) {
                    this.TongCongNhapField = value;
                    this.RaisePropertyChanged("TongCongNhap");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChiTietPhieuNhap_ServiceReference.IChiTietPhieuNhapService")]
    public interface IChiTietPhieuNhapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietPhieuNhapService/GetChiTietPhieuNhapById", ReplyAction="http://tempuri.org/IChiTietPhieuNhapService/GetChiTietPhieuNhapByIdResponse")]
        WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap GetChiTietPhieuNhapById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietPhieuNhapService/GetChiTietPhieuNhapById", ReplyAction="http://tempuri.org/IChiTietPhieuNhapService/GetChiTietPhieuNhapByIdResponse")]
        System.Threading.Tasks.Task<WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap> GetChiTietPhieuNhapByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietPhieuNhapService/GetAllChiTietPhieuNhap", ReplyAction="http://tempuri.org/IChiTietPhieuNhapService/GetAllChiTietPhieuNhapResponse")]
        WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap[] GetAllChiTietPhieuNhap();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietPhieuNhapService/GetAllChiTietPhieuNhap", ReplyAction="http://tempuri.org/IChiTietPhieuNhapService/GetAllChiTietPhieuNhapResponse")]
        System.Threading.Tasks.Task<WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap[]> GetAllChiTietPhieuNhapAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietPhieuNhapService/InsertChiTietPhieuNhap", ReplyAction="http://tempuri.org/IChiTietPhieuNhapService/InsertChiTietPhieuNhapResponse")]
        void InsertChiTietPhieuNhap(WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietPhieuNhapService/InsertChiTietPhieuNhap", ReplyAction="http://tempuri.org/IChiTietPhieuNhapService/InsertChiTietPhieuNhapResponse")]
        System.Threading.Tasks.Task InsertChiTietPhieuNhapAsync(WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietPhieuNhapService/UpdateChiTietPhieuNhap", ReplyAction="http://tempuri.org/IChiTietPhieuNhapService/UpdateChiTietPhieuNhapResponse")]
        void UpdateChiTietPhieuNhap(WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietPhieuNhapService/UpdateChiTietPhieuNhap", ReplyAction="http://tempuri.org/IChiTietPhieuNhapService/UpdateChiTietPhieuNhapResponse")]
        System.Threading.Tasks.Task UpdateChiTietPhieuNhapAsync(WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietPhieuNhapService/DeleteChiTietPhieuNhap", ReplyAction="http://tempuri.org/IChiTietPhieuNhapService/DeleteChiTietPhieuNhapResponse")]
        void DeleteChiTietPhieuNhap(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTietPhieuNhapService/DeleteChiTietPhieuNhap", ReplyAction="http://tempuri.org/IChiTietPhieuNhapService/DeleteChiTietPhieuNhapResponse")]
        System.Threading.Tasks.Task DeleteChiTietPhieuNhapAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChiTietPhieuNhapServiceChannel : WinTier.ChiTietPhieuNhap_ServiceReference.IChiTietPhieuNhapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChiTietPhieuNhapServiceClient : System.ServiceModel.ClientBase<WinTier.ChiTietPhieuNhap_ServiceReference.IChiTietPhieuNhapService>, WinTier.ChiTietPhieuNhap_ServiceReference.IChiTietPhieuNhapService {
        
        public ChiTietPhieuNhapServiceClient() {
        }
        
        public ChiTietPhieuNhapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChiTietPhieuNhapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChiTietPhieuNhapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChiTietPhieuNhapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap GetChiTietPhieuNhapById(int id) {
            return base.Channel.GetChiTietPhieuNhapById(id);
        }
        
        public System.Threading.Tasks.Task<WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap> GetChiTietPhieuNhapByIdAsync(int id) {
            return base.Channel.GetChiTietPhieuNhapByIdAsync(id);
        }
        
        public WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap[] GetAllChiTietPhieuNhap() {
            return base.Channel.GetAllChiTietPhieuNhap();
        }
        
        public System.Threading.Tasks.Task<WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap[]> GetAllChiTietPhieuNhapAsync() {
            return base.Channel.GetAllChiTietPhieuNhapAsync();
        }
        
        public void InsertChiTietPhieuNhap(WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap obj) {
            base.Channel.InsertChiTietPhieuNhap(obj);
        }
        
        public System.Threading.Tasks.Task InsertChiTietPhieuNhapAsync(WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap obj) {
            return base.Channel.InsertChiTietPhieuNhapAsync(obj);
        }
        
        public void UpdateChiTietPhieuNhap(WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap obj) {
            base.Channel.UpdateChiTietPhieuNhap(obj);
        }
        
        public System.Threading.Tasks.Task UpdateChiTietPhieuNhapAsync(WinTier.ChiTietPhieuNhap_ServiceReference.ChiTietPhieuNhap obj) {
            return base.Channel.UpdateChiTietPhieuNhapAsync(obj);
        }
        
        public void DeleteChiTietPhieuNhap(int id) {
            base.Channel.DeleteChiTietPhieuNhap(id);
        }
        
        public System.Threading.Tasks.Task DeleteChiTietPhieuNhapAsync(int id) {
            return base.Channel.DeleteChiTietPhieuNhapAsync(id);
        }
    }
}
