//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTier.PhieuNhap_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhieuNhap", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class PhieuNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaNCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaNhanVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaPhieuNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TongTienNhapField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaNCC {
            get {
                return this.MaNCCField;
            }
            set {
                if ((this.MaNCCField.Equals(value) != true)) {
                    this.MaNCCField = value;
                    this.RaisePropertyChanged("MaNCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaNhanVien {
            get {
                return this.MaNhanVienField;
            }
            set {
                if ((this.MaNhanVienField.Equals(value) != true)) {
                    this.MaNhanVienField = value;
                    this.RaisePropertyChanged("MaNhanVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaPhieuNhap {
            get {
                return this.MaPhieuNhapField;
            }
            set {
                if ((this.MaPhieuNhapField.Equals(value) != true)) {
                    this.MaPhieuNhapField = value;
                    this.RaisePropertyChanged("MaPhieuNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayNhap {
            get {
                return this.NgayNhapField;
            }
            set {
                if ((this.NgayNhapField.Equals(value) != true)) {
                    this.NgayNhapField = value;
                    this.RaisePropertyChanged("NgayNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TongTienNhap {
            get {
                return this.TongTienNhapField;
            }
            set {
                if ((this.TongTienNhapField.Equals(value) != true)) {
                    this.TongTienNhapField = value;
                    this.RaisePropertyChanged("TongTienNhap");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhieuNhap_ServiceReference.IPhieuNhapService")]
    public interface IPhieuNhapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService/GetPhieuNhapById", ReplyAction="http://tempuri.org/IPhieuNhapService/GetPhieuNhapByIdResponse")]
        WinTier.PhieuNhap_ServiceReference.PhieuNhap GetPhieuNhapById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService/GetPhieuNhapById", ReplyAction="http://tempuri.org/IPhieuNhapService/GetPhieuNhapByIdResponse")]
        System.Threading.Tasks.Task<WinTier.PhieuNhap_ServiceReference.PhieuNhap> GetPhieuNhapByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService/GetAllPhieuNhap", ReplyAction="http://tempuri.org/IPhieuNhapService/GetAllPhieuNhapResponse")]
        WinTier.PhieuNhap_ServiceReference.PhieuNhap[] GetAllPhieuNhap();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService/GetAllPhieuNhap", ReplyAction="http://tempuri.org/IPhieuNhapService/GetAllPhieuNhapResponse")]
        System.Threading.Tasks.Task<WinTier.PhieuNhap_ServiceReference.PhieuNhap[]> GetAllPhieuNhapAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService/InsertPhieuNhap", ReplyAction="http://tempuri.org/IPhieuNhapService/InsertPhieuNhapResponse")]
        void InsertPhieuNhap(WinTier.PhieuNhap_ServiceReference.PhieuNhap obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService/InsertPhieuNhap", ReplyAction="http://tempuri.org/IPhieuNhapService/InsertPhieuNhapResponse")]
        System.Threading.Tasks.Task InsertPhieuNhapAsync(WinTier.PhieuNhap_ServiceReference.PhieuNhap obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService/UpdatePhieuNhap", ReplyAction="http://tempuri.org/IPhieuNhapService/UpdatePhieuNhapResponse")]
        void UpdatePhieuNhap(WinTier.PhieuNhap_ServiceReference.PhieuNhap obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService/UpdatePhieuNhap", ReplyAction="http://tempuri.org/IPhieuNhapService/UpdatePhieuNhapResponse")]
        System.Threading.Tasks.Task UpdatePhieuNhapAsync(WinTier.PhieuNhap_ServiceReference.PhieuNhap obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService/DeletePhieuNhap", ReplyAction="http://tempuri.org/IPhieuNhapService/DeletePhieuNhapResponse")]
        void DeletePhieuNhap(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService/DeletePhieuNhap", ReplyAction="http://tempuri.org/IPhieuNhapService/DeletePhieuNhapResponse")]
        System.Threading.Tasks.Task DeletePhieuNhapAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService/GetMaxId", ReplyAction="http://tempuri.org/IPhieuNhapService/GetMaxIdResponse")]
        int GetMaxId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService/GetMaxId", ReplyAction="http://tempuri.org/IPhieuNhapService/GetMaxIdResponse")]
        System.Threading.Tasks.Task<int> GetMaxIdAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhieuNhapServiceChannel : WinTier.PhieuNhap_ServiceReference.IPhieuNhapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhieuNhapServiceClient : System.ServiceModel.ClientBase<WinTier.PhieuNhap_ServiceReference.IPhieuNhapService>, WinTier.PhieuNhap_ServiceReference.IPhieuNhapService {
        
        public PhieuNhapServiceClient() {
        }
        
        public PhieuNhapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhieuNhapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhieuNhapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhieuNhapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinTier.PhieuNhap_ServiceReference.PhieuNhap GetPhieuNhapById(int id) {
            return base.Channel.GetPhieuNhapById(id);
        }
        
        public System.Threading.Tasks.Task<WinTier.PhieuNhap_ServiceReference.PhieuNhap> GetPhieuNhapByIdAsync(int id) {
            return base.Channel.GetPhieuNhapByIdAsync(id);
        }
        
        public WinTier.PhieuNhap_ServiceReference.PhieuNhap[] GetAllPhieuNhap() {
            return base.Channel.GetAllPhieuNhap();
        }
        
        public System.Threading.Tasks.Task<WinTier.PhieuNhap_ServiceReference.PhieuNhap[]> GetAllPhieuNhapAsync() {
            return base.Channel.GetAllPhieuNhapAsync();
        }
        
        public void InsertPhieuNhap(WinTier.PhieuNhap_ServiceReference.PhieuNhap obj) {
            base.Channel.InsertPhieuNhap(obj);
        }
        
        public System.Threading.Tasks.Task InsertPhieuNhapAsync(WinTier.PhieuNhap_ServiceReference.PhieuNhap obj) {
            return base.Channel.InsertPhieuNhapAsync(obj);
        }
        
        public void UpdatePhieuNhap(WinTier.PhieuNhap_ServiceReference.PhieuNhap obj) {
            base.Channel.UpdatePhieuNhap(obj);
        }
        
        public System.Threading.Tasks.Task UpdatePhieuNhapAsync(WinTier.PhieuNhap_ServiceReference.PhieuNhap obj) {
            return base.Channel.UpdatePhieuNhapAsync(obj);
        }
        
        public void DeletePhieuNhap(int id) {
            base.Channel.DeletePhieuNhap(id);
        }
        
        public System.Threading.Tasks.Task DeletePhieuNhapAsync(int id) {
            return base.Channel.DeletePhieuNhapAsync(id);
        }
        
        public int GetMaxId() {
            return base.Channel.GetMaxId();
        }
        
        public System.Threading.Tasks.Task<int> GetMaxIdAsync() {
            return base.Channel.GetMaxIdAsync();
        }
    }
}
