//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHangEntity
    {
        public int ID { get; set; }
        public int MaDonDatHang { get; set; }
        public int MaSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<double> TongCong { get; set; }
    
        public virtual DonDatHangEntity DonDatHang { get; set; }
        public virtual SanPhamEntity SanPham { get; set; }
    }
}
