//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCapEntity
    {
        public NhaCungCapEntity()
        {
            this.PhieuNhap = new HashSet<PhieuNhapEntity>();
        }
    
        public int MaNCC { get; set; }
        public string TenNCC { get; set; }
        public string DiaChiNCC { get; set; }
        public string SoDTNCC { get; set; }
        public string EmailNCC { get; set; }
    
        public virtual ICollection<PhieuNhapEntity> PhieuNhap { get; set; }
    }
}
