//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaSanXuatEntity
    {
        public NhaSanXuatEntity()
        {
            this.SanPham = new HashSet<SanPhamEntity>();
        }
    
        public int MaNSX { get; set; }
        public string TenNSX { get; set; }
        public string GioiThieuNSX { get; set; }
    
        public virtual ICollection<SanPhamEntity> SanPham { get; set; }
    }
}
