//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapEntity
    {
        public PhieuNhapEntity()
        {
            this.ChiTietPhieuNhap = new HashSet<ChiTietPhieuNhapEntity>();
        }
    
        public int MaPhieuNhap { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<double> TongTienNhap { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
    
        public virtual ICollection<ChiTietPhieuNhapEntity> ChiTietPhieuNhap { get; set; }
        public virtual NhaCungCapEntity NhaCungCap { get; set; }
        public virtual NhanVienEntity NhanVien { get; set; }
    }
}
