//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamEntity
    {
        public SanPhamEntity()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHangEntity>();
            this.ChiTietPhieuNhap = new HashSet<ChiTietPhieuNhapEntity>();
            this.TonKho = new HashSet<TonKhoEntity>();
        }
    
        public int MaSanPham { get; set; }
        public Nullable<int> MaNSX { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string TenSanPham { get; set; }
        public string MoTaSanPham { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
        public string HinhLon { get; set; }
        public string HinhNho { get; set; }
        public string ManHinh { get; set; }
        public string HDH { get; set; }
        public string BoXuLy { get; set; }
        public string BoNho { get; set; }
        public string C3G { get; set; }
        public string WLan { get; set; }
        public string Camera { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<double> Gia { get; set; }
        public string TinhNang { get; set; }
    
        public virtual ICollection<ChiTietDonHangEntity> ChiTietDonHang { get; set; }
        public virtual ICollection<ChiTietPhieuNhapEntity> ChiTietPhieuNhap { get; set; }
        public virtual LoaiSanPhamEntity LoaiSanPham { get; set; }
        public virtual NhaSanXuatEntity NhaSanXuat { get; set; }
        public virtual ICollection<TonKhoEntity> TonKho { get; set; }
    }
}
