//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TMobileDBEntities : DbContext
    {
        public TMobileDBEntities()
            : base("name=TMobileDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHangEntity> ChiTietDonHang { get; set; }
        public virtual DbSet<ChiTietPhieuNhapEntity> ChiTietPhieuNhap { get; set; }
        public virtual DbSet<ChucVuEntity> ChucVu { get; set; }
        public virtual DbSet<DonDatHangEntity> DonDatHang { get; set; }
        public virtual DbSet<LoaiSanPhamEntity> LoaiSanPham { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<NhaCungCapEntity> NhaCungCap { get; set; }
        public virtual DbSet<NhanVienEntity> NhanVien { get; set; }
        public virtual DbSet<NhaSanXuatEntity> NhaSanXuat { get; set; }
        public virtual DbSet<PhieuNhapEntity> PhieuNhap { get; set; }
        public virtual DbSet<SanPhamEntity> SanPham { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TuVanEntity> TuVan { get; set; }
        public virtual DbSet<TrangThaiHoaDonEntity> TrangThaiHoaDon { get; set; }
        public virtual DbSet<UserEntity> User { get; set; }
        public virtual DbSet<TonKhoEntity> TonKho { get; set; }
    }
}
