//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonKhoEntity
    {
        public int MaSanPham { get; set; }
        public int SoLuongTon { get; set; }
        public System.DateTime NgayTon { get; set; }
    
        public virtual SanPhamEntity SanPham { get; set; }
    }
}
