//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangThaiHoaDonEntity
    {
        public TrangThaiHoaDonEntity()
        {
            this.DonDatHang = new HashSet<DonDatHangEntity>();
        }
    
        public int TrangThai { get; set; }
        public string TenTrangThai { get; set; }
    
        public virtual ICollection<DonDatHangEntity> DonDatHang { get; set; }
    }
}
